Update security_scan.yml

diff --git a/.github/workflows/security_scan.yml b/.github/workflows/security_scan.yml
--- a/.github/workflows/security_scan.yml
+++ b/.github/workflows/security_scan.yml
@@ -68,12 +68,12 @@ jobs:
       - name: Debug EC2 Connectivity
         run: |
           echo "Testing Connection to EC2..."
-          curl -v --connect-timeout 10 --max-time 20 http://172.31.14.30:3000 || (echo "ERROR: Target is unreachable!" && exit 1)
+          curl -v --connect-timeout 10 --max-time 20 http://3.129.253.217:3000 || (echo "ERROR: Target is unreachable!" && exit 1)
 
       - name: Run OWASP ZAP Passive Scan (Optimized)
         uses: zaproxy/action-full-scan@v0.5.0
         with:
-          target: 'http://172.31.14.30:3000'
+          target: 'http://3.129.253.217:3000'
           docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
           cmd_options: >
             -m 0
